bot:
  # get bot token from https://t.me/botfather
  token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

vault:
  address: test
  pki_mountpoint: pki_int_ca
  role: xxx
  ttl: 30d

team_chat_id: -100XXXXXXXXXXXXX
logs_chat_id: -100XXXXXXXXXXXXX

vpn_servers: [ 
  {"name": "srv1", "host" : "server1.io", "port": 2233, "routes": ["X.X.X.X"]},
  {"name": "srv2", "host" : "server2.io", "port": 3344, "routes": ["X.X.X.X"]},
]